CREATE DATABASE music_site WITH OWNER = postgres;

\c music_site;

CREATE TABLE IF NOT EXISTS Genres (
    GenreID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists (
    ArtistID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistGenres (
    ArtistGenreID INT PRIMARY KEY AUTO_INCREMENT,
    ArtistID INT,
    GenreID INT,
    FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID),
    FOREIGN KEY (GenreID) REFERENCES Genres(GenreID)
);

CREATE TABLE IF NOT EXISTS Albums (
    AlbumID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(100) NOT NULL,
    ReleaseYear YEAR
);

CREATE TABLE IF NOT EXISTS AlbumArtists (
    AlbumArtistID INT PRIMARY KEY AUTO_INCREMENT,
    AlbumID INT,
    ArtistID INT,
    FOREIGN KEY (AlbumID) REFERENCES Albums(AlbumID),
    FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID)
);

CREATE TABLE IF NOT EXISTS Tracks (
    TrackID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(100) NOT NULL,
    Duration TIME,
    AlbumID INT,
    FOREIGN KEY (AlbumID) REFERENCES Albums(AlbumID)
);

CREATE TABLE IF NOT EXISTS Compilations (
    CompilationID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(100) NOT NULL,
    ReleaseYear YEAR
);

CREATE TABLE IF NOT EXISTS CompilationTracks (
    CompilationTrackID INT PRIMARY KEY AUTO_INCREMENT,
    CompilationID INT,
    TrackID INT,
    FOREIGN KEY (CompilationID) REFERENCES Compilations(CompilationID),
    FOREIGN KEY (TrackID) REFERENCES Tracks(TrackID)
);